import { ReactNode } from "react";
import type { Metadata } from "next";
import { ConfigProvider } from "antd";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { NextIntlClientProvider, useMessages } from "next-intl";

import "./globals.css";
import { locales } from "@/navigation";
// import { GameProvider } from '@/contexts/use-game';
import { ReactQueryProvider } from "@/utils/providers/react-query.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: ReactNode;
  params: { locale: string };
}>) {
  if (!locales.includes(locale)) {
    notFound();
  }

  const messages = useMessages();

  return (
    <html lang={locale}>
      <AntdRegistry>
        <ConfigProvider>
          <NextIntlClientProvider {...{ locales, messages }}>
            <ReactQueryProvider>
              <body className={inter.className}>
                <div className="flex flex-col h-screen">
                  <header className="py-2 bg-gray-700 text-white text-center">
                    Sticky Header and Footer with Tailwind
                  </header>
                  <div className="flex-1 overflow-y-auto">{children}</div>
                  <footer className="py-2 bg-gray-700 text-center text-white">
                    napfernandes@2024
                  </footer>
                </div>
              </body>
            </ReactQueryProvider>
          </NextIntlClientProvider>
        </ConfigProvider>
      </AntdRegistry>
    </html>
  );
}
